# Generated by Django 3.2.25 on 2025-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='search_url_format',
            field=models.TextField(blank=True, help_text='URL format for searching, e.g., "https://example.com/search?q={query}"'),
        ),
    ]
