# Generated by Django 3.2.25 on 2025-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_newssource_search_url_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('published_time', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='search_url_format',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['keyword'], name='newsapp_art_keyword_77c495_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_hash'], name='newsapp_art_content_56d08e_idx'),
        ),
    ]
